// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

// ─── OpenZeppelin Imports ────────────────────────────────────────────────────
import "@openzeppelin/contracts/token/ERC20/IERC20.sol";
import "@openzeppelin/contracts/token/ERC20/utils/SafeERC20.sol";
import "@openzeppelin/contracts/access/Ownable.sol";
import "@openzeppelin/contracts/utils/ReentrancyGuard.sol";
import "@openzeppelin/contracts/utils/Pausable.sol";

/**
 * @title Escrow
 * @author XBorder Payment System
 * @notice Trustless USDC escrow for Nigeria ↔ Ghana cross-border payments.
 *
 * @dev ARCHITECTURE OVERVIEW:
 *
 *  1. Sender calls deposit() with USDC amount + unique txId from backend
 *  2. Contract locks USDC, emits TransferInitiated
 *  3. Relayer service (off-chain) watches for TransferInitiated events
 *  4. Relayer calls completeTransfer() after backend confirms off-ramp
 *  5. USDC released to recipient, fee taken, emits TransferCompleted
 *
 *  SECURITY MODEL:
 *  - ReentrancyGuard: prevents reentrancy attacks on all state-changing functions
 *  - SafeERC20: handles non-standard ERC20 tokens safely (not needed for USDC
 *    but correct pattern for production — token address could change)
 *  - Pausable: emergency stop controlled by owner
 *  - Two-role system: owner (admin) vs relayer (operator)
 *  - Transfer state machine: PENDING → COMPLETED | CANCELLED (no going back)
 *
 *  FEE MODEL:
 *  - Flat basis-point fee on deposit amount
 *  - Fee held in contract, withdrawable by owner
 *  - Recipient receives: amount - fee
 *  - 1 basis point = 0.01% (100 bps = 1%)
 */
contract Escrow is Ownable, ReentrancyGuard, Pausable {

    // ─── SafeERC20 ───────────────────────────────────────────────────────────
    using SafeERC20 for IERC20;

    // ─── Types ───────────────────────────────────────────────────────────────

    /// @notice All possible states of a transfer
    /// @dev State machine: PENDING is the only mutable state
    enum TransferStatus {
        PENDING,    // Funds locked, awaiting completion
        COMPLETED,  // Funds released to recipient
        CANCELLED   // Funds refunded to sender
    }

    /// @notice Full transfer record stored on-chain
    struct Transfer {
        bytes32 txId;           // Unique ID generated by backend
        address sender;         // Who deposited
        address recipient;      // Who receives on completion
        uint256 amount;         // Gross amount deposited (before fee)
        uint256 fee;            // Fee held at deposit time
        uint256 netAmount;      // amount - fee (what recipient gets)
        uint64  createdAt;      // Block timestamp of deposit
        uint64  completedAt;    // Block timestamp of completion/cancellation
        TransferStatus status;  // Current state
    }

    // ─── State Variables ─────────────────────────────────────────────────────

    /// @notice The USDC token contract this escrow accepts
    IERC20 public immutable usdcToken;

    /// @notice Address authorised to complete/cancel transfers
    /// @dev Rotatable by owner — allows key rotation without redeploying
    address public relayer;

    /// @notice Address that receives collected fees
    address public feeRecipient;

    /// @notice Fee in basis points (1 bp = 0.01%)
    /// @dev Default: 50 bps = 0.5% per transfer
    uint256 public feeBasisPoints;

    /// @notice Maximum allowed fee — hardcoded safety cap
    /// @dev 500 bps = 5% max. Protects users from admin abuse.
    uint256 public constant MAX_FEE_BASIS_POINTS = 500;

    /// @notice Basis point denominator
    uint256 public constant BASIS_POINTS_DENOMINATOR = 10_000;

    /// @notice Minimum deposit amount: 1 USDC (in raw units)
    uint256 public constant MIN_DEPOSIT_AMOUNT = 1 * 10 ** 6;

    /// @notice Maximum deposit amount: 50,000 USDC (in raw units)
    /// @dev Operational limit — can be raised by owner via setDepositLimits()
    uint256 public maxDepositAmount;

    /// @notice Total fees accumulated (not yet withdrawn)
    uint256 public accumulatedFees;

    /// @notice All transfers by their unique txId
    mapping(bytes32 => Transfer) public transfers;

    /// @notice Tracks whether a txId has ever been used
    /// @dev Separate from transfers mapping to detect replays on cancelled txs
    mapping(bytes32 => bool) public txIdUsed;

    // ─── Events ──────────────────────────────────────────────────────────────

    /**
     * @notice Emitted when a sender locks USDC into escrow
     * @param txId        Unique transfer ID (from backend)
     * @param sender      Address that deposited
     * @param recipient   Intended recipient on completion
     * @param amount      Gross amount deposited
     * @param fee         Fee deducted from amount
     * @param netAmount   Amount recipient will receive
     * @param timestamp   Block timestamp
     */
    event TransferInitiated(
        bytes32 indexed txId,
        address indexed sender,
        address indexed recipient,
        uint256 amount,
        uint256 fee,
        uint256 netAmount,
        uint64  timestamp
    );

    /**
     * @notice Emitted when relayer releases funds to recipient
     * @param txId        Transfer ID
     * @param recipient   Address that received funds
     * @param netAmount   Amount transferred to recipient
     * @param timestamp   Block timestamp
     */
    event TransferCompleted(
        bytes32 indexed txId,
        address indexed recipient,
        uint256 netAmount,
        uint64  timestamp
    );

    /**
     * @notice Emitted when relayer refunds sender
     * @param txId        Transfer ID
     * @param sender      Address that was refunded
     * @param amount      Gross amount refunded (full amount, no fee on cancel)
     * @param timestamp   Block timestamp
     */
    event TransferCancelled(
        bytes32 indexed txId,
        address indexed sender,
        uint256 amount,
        uint64  timestamp
    );

    /**
     * @notice Emitted when owner withdraws accumulated fees
     * @param recipient   Where fees were sent
     * @param amount      Total fees withdrawn
     */
    event FeesWithdrawn(address indexed recipient, uint256 amount);

    /**
     * @notice Emitted when the relayer address is rotated
     * @param oldRelayer  Previous relayer
     * @param newRelayer  New relayer
     */
    event RelayerUpdated(address indexed oldRelayer, address indexed newRelayer);

    /**
     * @notice Emitted when fee basis points are updated
     * @param oldFee  Previous fee in bps
     * @param newFee  New fee in bps
     */
    event FeeUpdated(uint256 oldFee, uint256 newFee);

    // ─── Custom Errors ───────────────────────────────────────────────────────

    error NotRelayer(address caller);
    error TxIdAlreadyUsed(bytes32 txId);
    error TransferNotPending(bytes32 txId, TransferStatus status);
    error InvalidRecipient();
    error InvalidRelayer();
    error AmountBelowMinimum(uint256 amount, uint256 minimum);
    error AmountAboveMaximum(uint256 amount, uint256 maximum);
    error ZeroAmount();
    error ZeroAddress();
    error FeeTooHigh(uint256 fee, uint256 maxFee);
    error NoFeesToWithdraw();
    error InsufficientContractBalance();

    // ─── Modifiers ───────────────────────────────────────────────────────────

    /// @notice Restricts function to the authorised relayer address
    modifier onlyRelayer() {
        if (msg.sender != relayer) revert NotRelayer(msg.sender);
        _;
    }

    // ─── Constructor ─────────────────────────────────────────────────────────

    /**
     * @param _usdcToken       Address of the MockUSDC (or real USDC) contract
     * @param _relayer         Initial relayer address
     * @param _feeRecipient    Address to receive fees
     * @param _feeBasisPoints  Initial fee in basis points (e.g. 50 = 0.5%)
     * @param _initialOwner    Contract owner address
     */
    constructor(
        address _usdcToken,
        address _relayer,
        address _feeRecipient,
        uint256 _feeBasisPoints,
        address _initialOwner
    ) Ownable(_initialOwner) {
        // ── Validate all constructor args up front ───────────────────────────
        if (_usdcToken    == address(0)) revert ZeroAddress();
        if (_relayer      == address(0)) revert InvalidRelayer();
        if (_feeRecipient == address(0)) revert ZeroAddress();
        if (_initialOwner == address(0)) revert ZeroAddress();
        if (_feeBasisPoints > MAX_FEE_BASIS_POINTS) {
            revert FeeTooHigh(_feeBasisPoints, MAX_FEE_BASIS_POINTS);
        }

        usdcToken       = IERC20(_usdcToken);
        relayer         = _relayer;
        feeRecipient    = _feeRecipient;
        feeBasisPoints  = _feeBasisPoints;
        maxDepositAmount = 50_000 * 10 ** 6; // 50,000 USDC default
    }

    // ─── External: Sender ────────────────────────────────────────────────────

    /**
     * @notice Lock USDC into escrow to initiate a cross-border transfer
     *
     * @param txId       Unique transfer ID — generated by the backend
     * @param recipient  Address that will receive funds on completion
     * @param amount     Gross USDC amount in raw units (6 decimals)
     *
     * @dev FLOW:
     *  1. Validate inputs and txId uniqueness
     *  2. Calculate fee and net amount
     *  3. Pull USDC from sender (requires prior approval)
     *  4. Store transfer record
     *  5. Emit TransferInitiated
     *
     * @dev The sender MUST call usdcToken.approve(escrowAddress, amount)
     *      before calling this function. The frontend handles this.
     *
     * Emits {TransferInitiated}
     */
    function deposit(
        bytes32 txId,
        address recipient,
        uint256 amount
    )
        external
        nonReentrant
        whenNotPaused
    {
        // ── Input Validation ─────────────────────────────────────────────────
        if (txIdUsed[txId]) revert TxIdAlreadyUsed(txId);
        if (recipient == address(0)) revert InvalidRecipient();
        if (amount == 0) revert ZeroAmount();
        if (amount < MIN_DEPOSIT_AMOUNT) {
            revert AmountBelowMinimum(amount, MIN_DEPOSIT_AMOUNT);
        }
        if (amount > maxDepositAmount) {
            revert AmountAboveMaximum(amount, maxDepositAmount);
        }

        // ── Fee Calculation ──────────────────────────────────────────────────
        // fee = amount × feeBasisPoints / 10_000
        // Example: 100 USDC × 50 / 10_000 = 0.5 USDC fee
        uint256 fee = (amount * feeBasisPoints) / BASIS_POINTS_DENOMINATOR;
        uint256 netAmount = amount - fee;

        // ── Mark txId as used BEFORE transfer (CEI pattern) ─────────────────
        // Checks-Effects-Interactions: state change before external call
        txIdUsed[txId] = true;
        accumulatedFees += fee;

        // ── Store Transfer Record ────────────────────────────────────────────
        transfers[txId] = Transfer({
            txId:        txId,
            sender:      msg.sender,
            recipient:   recipient,
            amount:      amount,
            fee:         fee,
            netAmount:   netAmount,
            createdAt:   uint64(block.timestamp),
            completedAt: 0,
            status:      TransferStatus.PENDING
        });

        // ── Pull USDC from sender ────────────────────────────────────────────
        // SafeERC20.safeTransferFrom reverts on failure
        usdcToken.safeTransferFrom(msg.sender, address(this), amount);

        // ── Emit ─────────────────────────────────────────────────────────────
        emit TransferInitiated(
            txId,
            msg.sender,
            recipient,
            amount,
            fee,
            netAmount,
            uint64(block.timestamp)
        );
    }

    // ─── External: Relayer ───────────────────────────────────────────────────

    /**
     * @notice Release escrowed USDC to recipient — called by relayer
     *
     * @param txId  The transfer ID to complete
     *
     * @dev Called after backend confirms the off-ramp was successful.
     *      Only the relayer can call this.
     *
     * Emits {TransferCompleted}
     */
    function completeTransfer(bytes32 txId)
        external
        nonReentrant
        onlyRelayer
        whenNotPaused
    {
        Transfer storage transfer = transfers[txId];

        // ── Validate state ───────────────────────────────────────────────────
        if (transfer.status != TransferStatus.PENDING) {
            revert TransferNotPending(txId, transfer.status);
        }

        // ── State change BEFORE transfer (CEI) ──────────────────────────────
        transfer.status      = TransferStatus.COMPLETED;
        transfer.completedAt = uint64(block.timestamp);

        // ── Release net amount to recipient ──────────────────────────────────
        // Fee stays in contract (already tracked in accumulatedFees)
        usdcToken.safeTransfer(transfer.recipient, transfer.netAmount);

        // ── Emit ─────────────────────────────────────────────────────────────
        emit TransferCompleted(
            txId,
            transfer.recipient,
            transfer.netAmount,
            uint64(block.timestamp)
        );
    }

    /**
     * @notice Refund escrowed USDC to sender — called by relayer
     *
     * @param txId  The transfer ID to cancel
     *
     * @dev Called when off-ramp fails or times out.
     *      Full amount refunded — no fee on cancellation.
     *      Fee that was tracked in accumulatedFees is reversed.
     *
     * Emits {TransferCancelled}
     */
    function cancelTransfer(bytes32 txId)
        external
        nonReentrant
        onlyRelayer
    {
        Transfer storage transfer = transfers[txId];

        // ── Validate state ───────────────────────────────────────────────────
        if (transfer.status != TransferStatus.PENDING) {
            revert TransferNotPending(txId, transfer.status);
        }

        // ── Reverse fee accumulation — full refund ───────────────────────────
        accumulatedFees -= transfer.fee;

        // ── State change BEFORE transfer (CEI) ──────────────────────────────
        transfer.status      = TransferStatus.CANCELLED;
        transfer.completedAt = uint64(block.timestamp);

        // ── Refund full gross amount to sender ───────────────────────────────
        usdcToken.safeTransfer(transfer.sender, transfer.amount);

        // ── Emit ─────────────────────────────────────────────────────────────
        emit TransferCancelled(
            txId,
            transfer.sender,
            transfer.amount,
            uint64(block.timestamp)
        );
    }

    // ─── External: Owner ─────────────────────────────────────────────────────

    /**
     * @notice Withdraw all accumulated fees to feeRecipient
     * @dev Only owner can call this
     *
     * Emits {FeesWithdrawn}
     */
    function withdrawFees() external onlyOwner nonReentrant {
        uint256 amount = accumulatedFees;
        if (amount == 0) revert NoFeesToWithdraw();

        // CEI: zero out before transfer
        accumulatedFees = 0;

        usdcToken.safeTransfer(feeRecipient, amount);

        emit FeesWithdrawn(feeRecipient, amount);
    }

    /**
     * @notice Rotate the relayer address
     * @param newRelayer  New relayer address
     *
     * Emits {RelayerUpdated}
     */
    function updateRelayer(address newRelayer) external onlyOwner {
        if (newRelayer == address(0)) revert InvalidRelayer();

        address oldRelayer = relayer;
        relayer = newRelayer;

        emit RelayerUpdated(oldRelayer, newRelayer);
    }

    /**
     * @notice Update the fee basis points
     * @param newFeeBasisPoints  New fee in bps (max 500 = 5%)
     *
     * Emits {FeeUpdated}
     */
    function updateFee(uint256 newFeeBasisPoints) external onlyOwner {
        if (newFeeBasisPoints > MAX_FEE_BASIS_POINTS) {
            revert FeeTooHigh(newFeeBasisPoints, MAX_FEE_BASIS_POINTS);
        }

        uint256 oldFee = feeBasisPoints;
        feeBasisPoints = newFeeBasisPoints;

        emit FeeUpdated(oldFee, newFeeBasisPoints);
    }

    /**
     * @notice Update max deposit limit
     * @param newMax  New maximum deposit amount in raw USDC units
     */
    function setMaxDepositAmount(uint256 newMax) external onlyOwner {
        if (newMax == 0) revert ZeroAmount();
        maxDepositAmount = newMax;
    }

    /**
     * @notice Update fee recipient address
     * @param newFeeRecipient  Address to receive future fee withdrawals
     */
    function setFeeRecipient(address newFeeRecipient) external onlyOwner {
        if (newFeeRecipient == address(0)) revert ZeroAddress();
        feeRecipient = newFeeRecipient;
    }

    /**
     * @notice Pause all deposits and completions — emergency stop
     * @dev Cancellations remain available even when paused (user protection)
     */
    function pause() external onlyOwner {
        _pause();
    }

    /// @notice Unpause the contract
    function unpause() external onlyOwner {
        _unpause();
    }

    // ─── External: Views ─────────────────────────────────────────────────────

    /**
     * @notice Get full transfer details by txId
     * @param txId  Transfer ID to look up
     * @return      Full Transfer struct
     */
    function getTransfer(bytes32 txId)
        external
        view
        returns (Transfer memory)
    {
        return transfers[txId];
    }

    /**
     * @notice Check if a transfer is in PENDING state
     * @param txId  Transfer ID to check
     */
    function isPending(bytes32 txId) external view returns (bool) {
        return transfers[txId].status == TransferStatus.PENDING;
    }

    /**
     * @notice Get current USDC balance held by this contract
     * @dev Should equal sum of all pending netAmounts + accumulatedFees
     */
    function contractBalance() external view returns (uint256) {
        return usdcToken.balanceOf(address(this));
    }

    /**
     * @notice Calculate fee for a given amount without executing
     * @param amount  Gross amount in raw USDC units
     * @return fee       Fee amount
     * @return netAmount Amount after fee
     */
    function calculateFee(uint256 amount)
        external
        view
        returns (uint256 fee, uint256 netAmount)
    {
        fee = (amount * feeBasisPoints) / BASIS_POINTS_DENOMINATOR;
        netAmount = amount - fee;
    }
}